#!/bin/bash
#######################################################################
# Root
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer L'installation"; exit 1
  fi
}
allow_only_root
#######################################################################
# Vérification les dependences
# Téléchargement, deplacement, extraction, ...
wget france-opg.tk/FTP/All/cmd-site-maj-et-cls/file.zip
clear
read -p "Continuer ..."
mv file.zip /tmp/
echo "... [1/5]"
cd /tmp/
echo "... [2/5]"
unzip file.zip
echo "... [3/5]"
rm file.zip
echo "... [4/5]"
cd /tmp/file/
echo "... [5/5]"
#######################################################################
# Copie, ...
read -p "Continuer ..."
cp site-maj /usr/bin/
chmod +x /usr/bin/site-maj
echo "... [1/3]"
cp site-cls /usr/bin/
chmod +x /usr/bin/site-cls
echo "... [2/3]"
cp site-cls-maj /usr/bin/
chmod +x /usr/bin/site-cls-maj
echo "... [3/3]"
echo "Fin"
#######################################################################